language: node_js
node_js:
  - '8.10'
cache:
  directories:
    - node_modules
sudo: false
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - echo -e "{\"adapter\":\"postgres\",\"host\":\"127.0.0.1\",\"port\":\"5432\",\"user\":\"postgres\",\"password\":\"\",\"database\":\"travistest\"}" >> /home/travis/build/mrollinsiv/honor-g-and-g/config/db.json
  - echo -e "{\"justGiving\":{\"apiKey\":\"$JUST_GIVING_API\"}}" >> /home/travis/build/mrollinsiv/honor-g-and-g/config/private.json